import os
import glob
from shiny import App, ui, render, reactive

# Define the root path for reports
REPORTS_ROOT = os.path.join(os.path.dirname(__file__), "output", "delivery_tracker")

def get_available_reports():
    """Find all available HTML reports.
    Returns a dict mapping 'City - Date' to the full file path.
    """
    reports = {}
    if not os.path.exists(REPORTS_ROOT):
        return reports
    
    # Search for HTML files in city subfolders
    pattern = os.path.join(REPORTS_ROOT, "*", "*.html")
    for html_path in glob.glob(pattern):
        # Extract city and filename
        city = os.path.basename(os.path.dirname(html_path))
        filename = os.path.basename(html_path)
        
        # Create a readable label (e.g., "Freetown Rapport")
        label = f"{city} - {filename.replace('_Delivery data - daily tracker box.html', '')}"
        reports[label] = html_path
        
    return dict(sorted(reports.items()))

app_ui = ui.page_fluid(
    ui.panel_title("Delivery Tracker Dashboard"),
    ui.layout_sidebar(
        ui.sidebar(
            ui.input_select(
                "report_select", 
                "Select City/Report:", 
                choices=[] # Populated in server
            ),
            ui.hr(),
            ui.markdown(
                """
                ### About
                This dashboard displays delivery tracker data quality and productivity metrics.
                The reports are generated by the pipeline in the `code/` folder.
                """
            ),
        ),
        ui.output_ui("report_frame"),
    ),
)

def server(input, output, session):
    # Load available reports at startup
    reports = reactive.Value(get_available_reports())
    
    # Update select input with available reports
    @reactive.Effect
    def _():
        available = reports.get()
        if available:
            ui.update_select("report_select", choices=list(available.keys()))
        else:
            ui.update_select("report_select", choices={"No reports found": ""})

    @output
    @render.ui
    def report_frame():
        selected_label = input.report_select()
        available = reports.get()
        
        if not selected_label or selected_label not in available:
            return ui.p("Please select a report or generate one using the master script.")
        
        report_path = available[selected_label]
        
        try:
            with open(report_path, "r", encoding="utf-8") as f:
                content = f.read()
            return ui.HTML(content)
        except Exception as e:
            return ui.p(f"Error loading report: {str(e)}")

app = App(app_ui, server)
